feat: update reward cash instant
delta/dalal-street-android pull request #198
Opened 2021-03-04 06:33 UTC by dhruv1294

2021-03-04 12:04 UTC, ranaaditya requested changes

2021-03-04 12:04 UTC, ranaaditya commented on app/src/main/java/org/pragyan/dalal18/ui/MainActivity.kt
> +                                dailychallengeStatus.layoutParams.height = 75
remove this hardcoding !

2021-03-04 12:04 UTC, ranaaditya commented on app/src/main/java/org/pragyan/dalal18/ui/MainActivity.kt
> +                                toast("Daily challenge is closed")
can we make a marqueue intead of showing a **toast** ?

For referrence - see the main screen when the market is closed.

2021-03-05 02:41 UTC, avikumar15 approved these changes

2021-03-05 20:06 UTC, ranaaditya approved these changes

2021-03-05 20:08 UTC, merged